name = "lean-json-parser"
version = "0.1.0"
defaultTargets = ["lean-json-parser"]

[[require]]
name = "lean-test"
git = "https://github.com/tim-br/lean-test.git"

[[lean_lib]]
name = "LeanJsonParser"

[[lean_exe]]
name = "lean-json-parser"
root = "Main"

[[lean_exe]]
name = "tests"
root = "Tests"
